language: perl

perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

notifications:
  irc:
    channels:
      - "irc.perl.org#dancer-core"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    use_notice: true
before_install:
    - git config --global user.email "dancer-dev@dancer.pm"
    - git config --global user.name "Perl Dancer dev team"
install:
#Safe fails to install due to failing tests since version 2.35 on perl < 5.14
    - perl -E 'exit($] < 5.014)' || cpanm --no-skip-satisfied Safe || cpanm --no-skip-satisfied --notest Safe || { cat ~/.cpanm/build.log ; false ; }
#Moo fails to install without Class::Method::Modifiers since 2012/10/19 
    - cpanm --no-skip-satisfied Class::Method::Modifiers YAML::XS || { cat ~/.cpanm/build.log ; false ; }
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

# We do not need sudo. Setting this allows travis to use (Docker) containers on EC2
sudo: false

script:
    - dzil smoke --author --release
